### PR TITLE
types.of

### PR DESCRIPTION
**Pull request by arcnmx**
adds `types.of value` and implements `types.show` on top of it

builds on top of #40

Most of the PR diff is noise from the unmerged PRs, [see actual diff on the top commit here](https://github.com/arcnmx/nix-std/commit/typeof)

### CODE REVIEW

**Comment by chessai** [comment]
This also looks good, once we get #40 in, we can rebase and merge this one too!

**Comment by chessai** [comment]
Rebase away!

**Comment by chessai** [comment]
Is this still a WIP?

**Comment by chessai** [comment]
With the noise reduced, this looks much cleaner

**Comment by arcnmx** [comment]
> Is this still a WIP?

it is still a bit of an initial stab, but that just makes it a small change that can be iterated on later

**Pull request merged**
