### PR TITLE
add tuples

### PR DESCRIPTION
**Pull request by chessai**

### CODE REVIEW

**Comment by chessai** [comment]
ping @nprindle @arcnmx for review

**Review by kanwren — APPROVED** [review]
lgtm

**Review by arcnmx — APPROVED** [review]
reviving [my old lazy attempt](https://github.com/chessai/nix-std/pull/24/files#diff-cad910dd70ff7f6bccaaec5bc75427431e3d94bfdbab0646ea6bb89354df2960) eh? :stuck_out_tongue:

**Comment by chessai** [comment]
> reviving [my old lazy attempt](https://github.com/chessai/nix-std/pull/24/files#diff-cad910dd70ff7f6bccaaec5bc75427431e3d94bfdbab0646ea6bb89354df2960) eh? :stuck_out_tongue: 

I don't even remember this! I should add your `toPair`.

**Pull request merged**
