### PR TITLE
Omit nulls in TOML rendering

### PR DESCRIPTION
**Pull request by JonathanLorimer**

### CODE REVIEW

**Comment by chessai** [comment]
Please add a test case demonstrating this behaviour

**Comment by JonathanLorimer** [comment]
I see, in nix `"key" = null` is not the same as `"key"` being undefined

**Comment by dzmitry-lahoda** [comment]
I am not sure, nix **options** may be lacking. 

in reality there is not only boolean `null vs not`. there is ternary `null meaning that use default of underlying vs not null by some real value vs null was set explicitly` (null vs undefined vs value in js)

fix in terraform is this https://github.com/terranix/terranix/blob/fc9077ca02ab5681935dbf0ecd725c4d889b9275/core/default.nix#L6 . 

so it may depend on how target code interprets null problem.

I did not so this here https://github.com/NixOS/nixpkgs/blob/master/lib/options.nix 

So resonable for YAML gen help with that.

I am not sure if nix OPTIONS are model of all possible way config works (including https://github.com/hashicorp/terraform/blob/main/internal/command/jsonprovider/attribute.go https://github.com/hashicorp/terraform/blob/main/internal/configs/configschema/coerce_value.go and https://github.com/divnix/dmerge ).

Imho any solution which will be used without changing OPTIONS is GOOD, but still not final, but GOOD

**Comment by chessai** [comment]
> I see, in nix `"key" = null` is not the same as `"key"` being undefined

In a nix attrset, keys can have null values or just be absent. So 
```
{ key = null; x = 5; }
```
is different from
```
{ x = 5; }
```

Though, I'm not exactly sure how this is relevant. The function you changed is traversed over all of the values, and so while there could be instances of null values, there shouldn't be any keys that don't exist.

**Comment by JonathanLorimer** [comment]
@chessai its relevant because the tests are based on roundtripping, so if we elide nulls in toml generation, there is no way to recover them when generating an attrset from toml.

**Comment by chessai** [comment]
> @chessai its relevant because the tests are based on roundtripping, so if we elide nulls in toml generation, there is no way to recover them when generating an attrset from toml.

You can add a non-roundtripping test by using assertEquals or whatever i called it (on mobile)

assertEquals (toTOML myEpicValue) "something epic here"

**Comment by JonathanLorimer** [comment]
@chessai thats true, I just assumed that the roundtripping tests implied that the library wants roundtripping serde. Are you okay with a change that breaks roundtripping?

**Comment by chessai** [comment]
> @chessai thats true, I just assumed that the roundtripping tests implied that the library wants roundtripping serde. Are you okay with a change that breaks roundtripping?

Undecided - How do other TOML libraries behave? Rust, JS, Python, Haskell?

**Comment by JonathanLorimer** [comment]
@chessai how about I add a partially applied options argument to the function, maintain toToml as roundtripping, and add toTomlOmitNull to which doesn't roundtrip?

**Comment by chessai** [comment]
> @chessai how about I add a partially applied options argument to the function, maintain toToml as roundtripping, and add toTomlOmitNull to which doesn't roundtrip?

Yeah, I considered this. I think this is a fine approach.

**Comment by JonathanLorimer** [comment]
@chessai turns out `builtins.fromTOML` doesn't handle nulls in the TOML, so maybe the behaviour I proposed is actually correct!

try this:
```
nix-repl> builtins.fromTOML "x=null"
```

I added a null test case that demonstrates the null filtering (that is required to actually get `builtins.fromTOML` to work)

**Comment by chessai** [comment]
> @chessai turns out `builtins.fromTOML` doesn't handle nulls in the TOML, so maybe the behaviour I proposed is actually correct!
> 
> try this:
> ```
> nix-repl> builtins.fromTOML "x=null"
> ```
> 
> I added a null test case that demonstrates the null filtering (that is required to actually get `builtins.fromTOML` to work)

Okay, then this is probably fine

the encoding tests should probably be written with
```
encode(decode(encode(foo))) == encode(foo)
```

as pointed out to me by @kanwren

**Comment by JonathanLorimer** [comment]
Can I get a review @chessai ?

**Review by chessai — APPROVED** [review]

**Comment by chessai** [comment]
Thanks for the patch!

**Pull request merged**
